WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd49dba5ff0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/bde96db8-d792-4b6a-b32c-4e8704d783f9/url
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd49dba63e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/bde96db8-d792-4b6a-b32c-4e8704d783f9/url
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd49dba41f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/bde96db8-d792-4b6a-b32c-4e8704d783f9/url
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd49d8e0b80>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/bde96db8-d792-4b6a-b32c-4e8704d783f9
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd49d8e1090>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/bde96db8-d792-4b6a-b32c-4e8704d783f9
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd49d8e1270>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/bde96db8-d792-4b6a-b32c-4e8704d783f9