WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa26c26c580>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/167b9e64-34a4-4f19-b862-a36ae6dcf70b/url
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa26c26e6b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/167b9e64-34a4-4f19-b862-a36ae6dcf70b/url
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa26c26e500>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/167b9e64-34a4-4f19-b862-a36ae6dcf70b/url
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa26c279240>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/167b9e64-34a4-4f19-b862-a36ae6dcf70b
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa26c279360>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/167b9e64-34a4-4f19-b862-a36ae6dcf70b
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa26c27ad40>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/167b9e64-34a4-4f19-b862-a36ae6dcf70b